[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synker"
version = "0.0.6"
description = "A Python package for generating synthetic data."
authors = [
    {name = "Danial Haselibozchaloee", email = "dhaselib@gmail.com"}
]
license = {file = "LICENSE.txt"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas"
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools]
packages = ["synker"]
